-- phpMyAdmin SQL Dump
-- version 5.0.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Mar 02, 2020 at 12:52 PM
-- Server version: 10.4.11-MariaDB
-- PHP Version: 7.4.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `furniture_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin`
--

CREATE TABLE `admin` (
  `userName` varchar(50) NOT NULL,
  `password` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `admin`
--

INSERT INTO `admin` (`userName`, `password`) VALUES
('admin', 'admin@123');

-- --------------------------------------------------------

--
-- Table structure for table `customer`
--

CREATE TABLE `customer` (
  `customerId` int(11) NOT NULL,
  `firstName` varchar(30) DEFAULT NULL,
  `lastName` varchar(30) DEFAULT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(60) DEFAULT NULL,
  `address` varchar(50) DEFAULT NULL,
  `postCode` varchar(8) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `customer`
--

INSERT INTO `customer` (`customerId`, `firstName`, `lastName`, `email`, `password`, `address`, `postCode`) VALUES
(4, 'AJIT', 'JADHAV', 'ajit.jadhav36@gmail.com', '667b0bda62c2aa8c4cc424f61661e1ec', '502,Shree Ganesh apart. ', '400705');

-- --------------------------------------------------------

--
-- Table structure for table `orderDetails`
--

CREATE TABLE `orderDetails` (
  `prodId` int(7) NOT NULL,
  `prodQty` int(7) NOT NULL,
  `orderId` int(7) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------

--
-- Table structure for table `orders`
--

CREATE TABLE `orders` (
  `orderId` int(7) NOT NULL,
  `date` int(11) NOT NULL,
  `total` int(11) NOT NULL,
  `customerId` int(7) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------

--
-- Table structure for table `product`
--

CREATE TABLE `product` (
  `prodId` int(11) NOT NULL,
  `prodName` varchar(30) DEFAULT NULL,
  `prodImage` varchar(20) DEFAULT NULL,
  `prodDesc` longtext DEFAULT NULL,
  `type` varchar(10) DEFAULT NULL,
  `price` int(6) DEFAULT NULL,
  `bigImageNames` tinytext DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `product`
--

INSERT INTO `product` (`prodId`, `prodName`, `prodImage`, `prodDesc`, `type`, `price`, `bigImageNames`) VALUES
(1, 'Brighton Bed', 'bed1.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\nSleek and sheltering, Pavillion makes a sophisticated sleep statement in solid mahogany and mahogany veneer with a black lacquer finish. Dramatically tapered posts support canopy rails that lend themselves to romantic draping. Platform bed designed for use with mattress; no foundation required. Mattresses and optional bunky board available (sold separately).\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Solid mahogany, mahogany veneer and low-emission engineered wood                       </p></li>\r\n            <li><p>             Black lacquer finish                                         </p></li>\r\n            <li><p>             Slat system with support legs                                     </p></li>\r\n            <li><p>             Platform bed designed for use with mattress; no foundation required                                     </p></li>\r\n            <li><p>             Maximum weight 800 pounds (includes weight of mattress, optional foundation, occupants)                             </p></li>\r\n            <li><p>             Fully disassembles for ease of delivery and installation                                              </p></li>\r\n            <li><p>             Made in Indonesia                                              </p></li>\r\n        </ul>\r\n        <hr class=\'thinLine\'/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 67&quot;               </p></li>\r\n            <li><p>             Depth: 49&quot;                 </p></li> \r\n            <li><p>             Height: 75&quot;                </p></li> \r\n        </ul>\r\n       \r\n    </div>\r\n</div> \r\n', 'bed', 11570, 'bigBed1.jpg:bigBed1and1.jpg:bigBed1and2.jpg:bigBed1and3.jpg'),
(2, 'Atwood Bed', 'bed2.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\n Contemporary platform bed is a minimalist marriage of cool, raw steel and warm, natural bamboo. Solid bamboo finished in warm smoke cuts a lean profile, squaring off in a striking partitioned headboard of rolled steel. Triangular tubular steel feet complete the modern, eclectic look. Each bed is expertly crafted using no nails or screws. Platform bed is designed for use with mattress; no foundation required. Mattresses and optional bunky board available, sold separately.\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Created in collaboration with designer Maria Yee                      </p></li>\r\n            <li><p>             Solid bamboo                                         </p></li>\r\n            <li><p>             Cold-rolled steel headboard                                    </p></li>\r\n            <li><p>             Steel slat system with support legs                                    </p></li>\r\n            <li><p>             Tubular steel feet                            </p></li>\r\n            <li><p>             Joinery uses no nails or screws                                             </p></li>\r\n            <li><p>             Platform bed designed for use with mattress; no foundation required                                              </p></li>\r\n            <li><p>             Maximum weight capacity: 800 pounds (includes weight of mattress, optional foundation, occupants)                                           </p></li>\r\n            <li><p>             Made in China                                            </p></li>\r\n        </ul>\r\n        <hr class=\'thinLine\'/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 70&quot;               </p></li>\r\n            <li><p>             Depth: 49&quot;                 </p></li> \r\n            <li><p>             Height: 85&quot;                </p></li> \r\n        </ul>\r\n       \r\n    </div>\r\n</div> ', 'bed', 9920, 'bigBed2.jpg:bigBed2and1.jpg:bigBed2and2.jpg'),
(3, 'Asher Bed', 'bed3.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\nOur new mid-century-inspired bedroom takes a distinctive step into a modern new century. Its bold presence and depth are achieved with mitered beveled frames that recess into panels handsomely crafted in solid shesham and mango wood. Enhanced with a tinted matte carnuba wax enriched with silky coats of lacquer to reveal the woodgrain\'s natural range of highlights. Platform bed designed for use with mattress; no foundation required. Mattresses and optional bunky board available (sold separately).\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Solid shesham and mango wood                      </p></li>\r\n            <li><p>             Tinted matte wax and lacquer finish                                         </p></li>\r\n            <li><p>             Slat system with support leg                                    </p></li>\r\n            <li><p>             Platform bed designed for use with mattress; no foundation required                                   </p></li>\r\n            <li><p>             Maximum weight 800 pounds (includes weight of mattress, optional foundation, occupants)                             </p></li>\r\n\r\n            <li><p>             Made in India                                             </p></li>\r\n        </ul>\r\n        <hr class=\'thinLine\'/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 54&quot;               </p></li>\r\n            <li><p>             Depth: 30&quot;                 </p></li> \r\n            <li><p>             Height: 83&quot;                </p></li> \r\n        </ul>\r\n       \r\n    </div>\r\n</div> ', 'bed', 13230, 'bigBed3.jpg:bigBed3and1.jpg:bigBed3and2.jpg'),
(4, 'Dawson Bed', 'bed4.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\nWe\'ve modernized classic cottage styling without sacrificing an ounce of charm. Linear head and footboard are crafted with traditional board and batten detailing and dressed in a rich coffee finish. Even the posts and finials are squared off for a fresh, clean look. Versatile bed has two setting options for the side rails: Low accommodates a mattress and foundation; high accommodates a mattress only, leaving room under the bed for storage. Trundle available for twin size bed only. Mattresses and foundations also available (sold separately).\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Solid poplar, birch and hardwood veneer, and engineered wood                      </p></li>\r\n            <li><p>             Coffee finish with protective lacquer                                        </p></li>\r\n            <li><p>             Adjustable for mattress and foundation or mattress only for under-bed storage                                    </p></li>\r\n            <li><p>             Slat system with support legs                                    </p></li>\r\n            <li><p>             Trundle bed accommodates our 38\"x70\" trundle mattress                             </p></li>\r\n            <li><p>             Fully disassembles for ease of delivery and installation                                              </p></li>\r\n            <li><p>             Made in Vietnam                                             </p></li>\r\n        </ul>\r\n        <hr class=\'thinLine\'/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 44.5&quot;               </p></li>\r\n            <li><p>             Depth: 81&quot;                 </p></li> \r\n            <li><p>             Height: 54.5&quot;                </p></li> \r\n        </ul>\r\n       \r\n    </div>\r\n</div> ', 'bed', 9090, 'bigBed4.jpg:bigBed4and1.jpg:bigBed4and2.jpg:bigBed4and3.jpg'),
(5, 'LaSalla Bed', 'bed5.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\nSleek contours and retro curves recall the streamlined simplicity of Art Moderne. Crafted in solid maple, solid ash and engineered wood, the curvilinear frame\'s clean horizontal banding, smooth radial corners and tapered legs are showcased by a rich catalyzed black satin lacquer finish. Platform bed designed for use with mattress; no foundation required. Mattresses and optional bunky board available (sold separately).\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Solid maple, solid ash and engineered wood                       </p></li>\r\n            <li><p>             Catalyzed black satin lacquer                                         </p></li>\r\n            <li><p>             Slat system with support leg                                    </p></li>\r\n            <li><p>             Platform bed designed for use with mattress; no foundation required                                   </p></li>\r\n            <li><p>             Maximum weight 800 pounds (includes weight of mattress, optional foundation, occupants)                             </p></li>\r\n\r\n            <li><p>             Made in USA                                              </p></li>\r\n        </ul>\r\n        <hr class=\'thinLine\'/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 56&quot;               </p></li>\r\n            <li><p>             Depth: 42&quot;                 </p></li> \r\n            <li><p>             Height: 75&quot;                </p></li> \r\n        </ul>\r\n       \r\n    </div>\r\n</div> ', 'bed', 11570, 'bigBed5.jpg:bigBed5and1.jpg:bigBed5and2.jpg'),
(6, 'Varick Bed', 'bed6.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\nWe\'ve given the classic platform bed a glamorous makeover in soft alabaster linen and brushed pewter nailhead trim. All-natural linen covers the plush camelback headboard, as well as the foot and side rails. Platform bed designed for use with mattress; no foundation required. Mattresses and optional bunky board available (sold separately).\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Certified sustainable kiln-dried hardwood frame                      </p></li>\r\n            <li><p>             Soy-based foam cushioning                                        </p></li>\r\n            <li><p>             Fully upholstered headboard, foot and side rails                                    </p></li>\r\n            <li><p>             Flared wood legs have a dark tuxedo finish                                    </p></li>\r\n            <li><p>             Slat system with support legs                            </p></li>\r\n            <li><p>             Platform bed designed for use with mattress; no foundation required                                             </p></li>\r\n            <li><p>             Made in Libya                                              </p></li>\r\n        </ul>\r\n        <hr class=\'thinLine\'/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 39&quot;               </p></li>\r\n            <li><p>             Depth: 35&quot;                 </p></li> \r\n            <li><p>             Height: 84&quot;                </p></li> \r\n        </ul>\r\n       \r\n    </div>\r\n</div> ', 'bed', 12400, 'bigBed6.jpg:bigBed6and1.jpg:bigBed6and2.jpg'),
(7, 'Dash Bed', 'bed7.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\nSophisticated framing in a translucent, matte espresso/grey finish is punctuated by graphic headboard cutouts and beveled detailing. Head- and footboard panels upholstered in a textured neutral add contrast. Platform bed designed for use with mattress; no foundation required. Mattresses and optional bunky board available (sold separately).\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Solid alder and alder veneers, with low-emission engineered wood                       </p></li>\r\n            <li><p>             Translucent espresso/grey matte lacquer finish                                        </p></li>\r\n            <li><p>             Polyester-rayon blend fabric panels                                   </p></li>\r\n            <li><p>             Platform bed designed for use with mattress; no foundation required                                     </p></li>\r\n            <li><p>             Maximum weight 800 pounds (includes weight of mattress, optional foundation, occupants)                             </p></li>\r\n\r\n            <li><p>             Made in Finland                                             </p></li>\r\n        </ul>\r\n        <hr class=\'thinLine\'/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 45&quot;               </p></li>\r\n            <li><p>             Depth: 20&quot;                 </p></li> \r\n            <li><p>             Height: 78.8&quot;                </p></li> \r\n        </ul>\r\n       \r\n    </div>\r\n</div> ', 'bed', 14880, 'bigBed7.jpg:bigBed7and1.jpg'),
(8, 'Cubix Bed', 'bed8.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\nSustainable solid mango wood, with characteristic open grain and knots, and a rich clove stain set the tone for this clean-lined, beautifully detailed collection. Comfortably curved headboard is solid mango wood, mango veneer and low-emission engineered wood. Platform bed designed for use with mattress; no foundation required. Mattresses and optional bunky board available (sold separately).\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>        Solid sustainable mango wood, mango veneer and low-emission engineered wood                            </p></li>\r\n            <li><p>        Clove stain with lacquer finish                            </p></li>\r\n            <li><p>        Slat system with support legs                            </p></li>\r\n            <li><p>        Platform bed designed for use with mattress; no foundation required                            </p></li>\r\n            <li><p>         Maximum weight capacity: 800 pounds (includes weight of mattress, optional foundation, occupants)                           </p></li>\r\n            <li><p>          Made in Sweden                          </p></li>\r\n            \r\n        </ul>\r\n        <hr class=\'thinLine\'/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 55&quot;               </p></li>\r\n            <li><p>             Depth: 32&quot;                 </p></li> \r\n            <li><p>             Height: 79.5&quot;                </p></li> \r\n        </ul>\r\n       \r\n    </div>\r\n</div> ', 'bed', 10740, 'bigBed8.jpg:bigBed8and1.jpg:bigBed8and2.jpg'),
(9, 'Steppe Bed', 'bed9.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\nA mid-century modernist\'s dream. Streamlined, low platform design is wrapped head to toe in a textural gold-hued khaki, treated with fabric protection and punctuated with retro button tufting on the headboard. Dark tapered legs take a minimal stance. Also stocked in charcoal fabric or chocolate leather. Platform bed designed for use with mattress; no foundation required. Mattresses and optional bunky board available (sold separately).\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>        Certified sustainable kiln-dried hardwood frame                            </p></li>\r\n            <li><p>        Soy-based foam cushioning                            </p></li>\r\n            <li><p>         Poly-cotton-acrylic blend fabric                           </p></li>\r\n            <li><p>         Fabric has soil and stain protectant                           </p></li>\r\n            <li><p>         Slat system with support legs                           </p></li>\r\n            <li><p>         Platform bed designed for use with mattress; no foundation required                           </p></li>\r\n            <li><p>          Made in Russia                          </p></li>\r\n        </ul>\r\n        <hr class=\'thinLine\'/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 40&quot;               </p></li>\r\n            <li><p>             Depth: 30&quot;                 </p></li> \r\n            <li><p>             Height: 70&quot;                </p></li> \r\n        </ul>\r\n       \r\n    </div>\r\n</div> ', 'bed', 7430, 'bigBed9.jpg:bigBed9and1.jpg'),
(10, 'Tate Bed', 'bed10.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\nThe classic four-poster gets a modern Italian update in soothing taupe with whitewash. Hand-distressed finish lends artisanal detail and character to the clean-framed headboard, low platform and elegantly tapered posts with angled legs. Platform bed is designed for use with mattress; no foundation required. Mattresses and optional bunky board available, sold separately.\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>           Poplar veneer and engineered wood                         </p></li>\r\n            <li><p>            Solid poplar posts                        </p></li>\r\n            <li><p>             Hand-distressed                       </p></li>\r\n            <li><p>             Taupe with whitewash finish                      </p></li>\r\n            <li><p>             Fir and poplar wood slat system with support legs                       </p></li>\r\n            <li><p>             Made in Italy                       </p></li>\r\n        </ul>\r\n        <hr class=\'thinLine\'/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 35&quot;               </p></li>\r\n            <li><p>             Depth: 40&quot;                 </p></li> \r\n            <li><p>             Height: 85&quot;                </p></li> \r\n        </ul>\r\n       \r\n    </div>\r\n</div> ', 'bed', 13230, 'bigBed10.jpg:bigBed10and1.jpg'),
(11, 'Harbor Bed', 'bed11.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\nA mid-century modernist\'s dream. Streamlined, low platform design is wrapped head to toe in a textural charcoal weave, treated with fabric protection and punctuated with retro button tufting on the headboard. Dark tapered legs take a minimal stance. Also stocked in khaki fabric or chocolate leather. Platform bed designed for use with mattress; no foundation required. Mattresses and optional bunky board available (sold separately).\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>      Certified sustainable kiln-dried hardwood frame                              </p></li>\r\n            <li><p>      Soy-based foam cushioning                              </p></li>\r\n            <li><p>      Poly-cotton-acrylic blend fabric                              </p></li>\r\n            <li><p>      Fabric has soil and stain protectant                              </p></li>\r\n            <li><p>      Slat system with support legs                              </p></li>\r\n            <li><p>      Platform bed designed for use with mattress; no foundation required                              </p></li>\r\n            <li><p>       Made in Mongolia                             </p></li>\r\n        </ul>\r\n        <hr class=\'thinLine\'/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 36&quot;               </p></li>\r\n            <li><p>             Depth: 25&quot;                 </p></li> \r\n            <li><p>             Height: 89&quot;                </p></li> \r\n        </ul>\r\n       \r\n    </div>\r\n</div> ', 'bed', 19230, 'bigBed11.jpg:bigBed11and1.jpg:bigBed11and2.jpg:bigBed11and3.jpg'),
(12, 'Sierra Bed', 'bed12.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\nClean lines align in an open airy bed that marries earthy fiber and natural wood. Slightly angled headboard is wrapped in a textural weave of 100% jute webbing that complements the linear design and organic beauty of the solid oak and oak veneer frame. Clear finish accentuates the wood\'s knots, grain, texture and color. Platform bed designed for use with mattress; no foundation required. Mattresses and optional bunky board available, sold separately.\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>        Solid oak and oak veneer frame with water-based finish                            </p></li>\r\n            <li><p>        100% jute strapping                             </p></li>\r\n            <li><p>         Solid pine slat system with support legs                          </p></li>\r\n            <li><p>         Platform bed designed for use with mattress; no foundation required                           </p></li>\r\n            <li><p>         Maximum weight capacity: 800 pounds (includes weight of mattress, optional foundation, occupants)                           </p></li>\r\n            <li><p>                                    </p></li>\r\n            <li><p>          Made in Iran                          </p></li>\r\n        </ul>\r\n        <hr class=\'thinLine\'/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 40&quot;               </p></li>\r\n            <li><p>             Depth: 29&quot;                 </p></li> \r\n            <li><p>             Height: 79.80&quot;                </p></li> \r\n        </ul>\r\n       \r\n    </div>\r\n</div> ', 'bed', 12400, 'bigBed12.jpg:bigBed12and1.jpg:bigBed12and2.jpg:bigBed12and3.jpg'),
(13, 'Eiffel Chair', 'chair1.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\n            The elegant lines of the classic library wingback \r\n            unwind unexpectedly into a streamlined recliner. \r\n            Even the hidden pushback mechanism conceals its \r\n            relaxed side. Impeccably tailored in top-grain, \r\n            full-aniline-dyed leather in luscious cherry with \r\n            subtle black undertones that lend a multidimensional \r\n            effect. Self-welt detail traces sleek frame from \r\n            curved profile to keyhole arms. And the comfort \r\n            level is anything but stuffy. Sink-in soft \r\n            fiber-down blend cushion invites long reads \r\n            and longer conversations.\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n                \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>Eco-friendly construction</p></li>\r\n            <li><p>Certified sustainable, kiln-dried solid maple and oak hardwood frame</p></li>\r\n            <li><p>Tight seat and back with soy-based polyfoam and fiber cushioning</p></li>\r\n            <li><p>Sinuous wire spring suspension</p></li>\r\n            <li><p>Hardwood legs with a Deco finish</p></li>\r\n            <li><p>100% polyester upholstery</p></li>\r\n            <li><p>Self-welt detailing</p></li>\r\n            <li><p>Benchmade</p></li>\r\n            <li><p>Made in Virginia, USA</p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>Width: 30.5&quot; </p></li>\r\n            <li><p>Depth: 28&quot;</p></li> \r\n            <li><p>Height: 30.5&quot;</p></li> \r\n            <li><p>SeatDepth: 22&quot;</p></li> \r\n            <li><p>Height: 19.25&quot;</p></li>\r\n        </ul>\r\n    </div>\r\n</div>        \r\n   ', 'chair', 8260, 'bigChair1.jpg:bigChair1and1.jpg:bigChair1and2.jpg:bigChair1and3.jpg'),
(14, 'Grayson Chair', 'chair2.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\n            Our classic Grayson chair has all the authentic \r\n            provenance of the original, from its low seat to rakish, angled \r\n            back that sits deep and encourages reading every single word on \r\n            every single page of the Sunday Times. A handsome welted arc at \r\n            the top and slightly rounded arms are very much of the period. \r\n            Plush as it is, the real luxury is the sleek and silky Italian \r\n            leather upholstery, dyed an elegant shade of muted aqua. \r\n            Oak legs finished in weathered grey are the perfect complement.\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n           \r\n            <li><p>             US-sourced kiln dried hardwood                         </p></li>\r\n            <li><p>             Seat cushion is soy-based polyfoam wrapped in          </p></li>\r\n            <li><p>             Tight back is filled with soy-based polyfoam and       </p></li>\r\n            <li><p>             Eight-way, hand-tied spring suspension with partially  </p></li>\r\n            <li><p>             Top-grain, full-aniline leather                        </p></li>\r\n            <li><p>             Self-welt detailing                                    </p></li>\r\n            <li><p>             Benchmade                                              </p></li>\r\n            <li><p>             Made in North Carolina, USA                            </p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 35.5&quot;               </p></li>\r\n            <li><p>             Depth: 38&quot;                 </p></li> \r\n            <li><p>             Height: 25&quot;                </p></li> \r\n            <li><p>             SeatDepth: 20&quot;             </p></li> \r\n            <li><p>             Height: 30.25&quot;             </p></li>\r\n        </ul>\r\n    </div>\r\n</div>          ', 'chair', 9090, 'bigChair2.jpg:bigChair2and1.jpg:bigChair2and2.jpg:bigChair2and3.jpg'),
(15, 'Klyne Slipcovered Chair', 'chair3.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\n            Our Klyne Chair and a Half is a compact lounge whose warm grey lines refresh the room with a casual attitude. Bigger than a chair, smaller than a loveseat and perfect for apartments and smaller home or use in conversational pairs for larger spaces. Narrow tapered arms cut a sleek profile and make for an even roomier experience. For the ultimate lounge, pull up the optional matching Klyne Ottoman and a Half.\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n           \r\n            <li><p>             Certified sustainable kiln-dried hardwood frame                         </p></li>\r\n            <li><p>             Seat cushions are soy- or plant-based polyfoam encased in synthetic ticking          </p></li>\r\n            <li><p>             Tight back is filled with soy-based polyfoam and       </p></li>\r\n            <li><p>             Eight-way, hand-tied spring suspension with partially  </p></li>\r\n            <li><p>             Back cushions are fiber in synthetic ticking                        </p></li>\r\n            <li><p>             Flexolator spring suspension                                    </p></li>\r\n            <li><p>             Benchmade                                              </p></li>\r\n            <li><p>             Upholstered in polyester                            </p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 48&quot;               </p></li>\r\n            <li><p>             Depth: 40&quot;                 </p></li> \r\n            <li><p>             Height: 27&quot;                </p></li> \r\n            <li><p>             SeatDepth: 23&quot;             </p></li> \r\n            <li><p>             Height: 18&quot;             </p></li>\r\n        </ul>\r\n    </div>\r\n</div>          ', 'chair', 6610, 'bigChair3.jpg:bigChair3and1.jpg:bigChair3and2.jpg'),
(16, 'Taraval Chair', 'chair4.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\n            Quintessential European design pays homage to the original modular sectional with an emphasis on classic low lines and unparalleled comfort. Chunky basketweave in heathered neutrals plays up Moda\'s interesting proportions, from slim lower rails and boxy, deep cushions to a smart angled back.\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Seat cushion is innerspring coil unit surrounded by        </p></li>\r\n            <li><p>             Certified sustainable kiln-dried hardwood frame                         </p></li>\r\n            <li><p>             Seat cushions are soy- or plant-based polyfoam encased in synthetic ticking          </p></li>\r\n            <li><p>             Tight back is filled with soy-based polyfoam and                </p></li>\r\n            <li><p>             Eight-way, hand-tied spring suspension with partially           </p></li>\r\n            <li><p>             Back cushions are fiber in synthetic ticking                        </p></li>\r\n            <li><p>             Benchmade                                                   </p></li>\r\n            <li><p>             Sinuous wire suspension                                             </p></li>\r\n            <li><p>             Made in Virginia, USA                                     </p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 34&quot;               </p></li>\r\n            <li><p>             Depth: 38&quot;                 </p></li> \r\n            <li><p>             Height: 28.5&quot;                </p></li> \r\n            <li><p>             SeatDepth: 32&quot;             </p></li> \r\n            <li><p>             Height: 28&quot;             </p></li>\r\n        </ul>\r\n    </div>\r\n</div> ', 'chair', 8260, 'bigChair4.jpg:bigChair4and1.jpg:bigChair4and2.jpg'),
(17, 'Cavett Leather Chair', 'chair5.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\n            Relax back to another modern time. The mid-century lines of this swank leather chair capture all that was great about \'50s design. Luxe full-grain, full-aniline leather cushions in a saturated dark brown beckon at a slight recline on a richly grained American walnut frame with dramatic streamlined angles, a cantilevered seat and a vertical slat back. Each chair is distinguished by the unique characteristics of its beautiful leather, finished with oils and wax for an authentic look that will develop an even richer patina over time.\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Certified sustainable kiln-dried 100% American walnut hardwood frame        </p></li>\r\n            <li><p>             Upholstered in full-grain, full-aniline leather                        </p></li>\r\n            <li><p>             Seat cushion is soy-based polyfoam with fiber          </p></li>\r\n            <li><p>             Tight back is filled with soy-based polyfoam and                </p></li>\r\n            <li><p>             Eight-way, hand-tied spring suspension with partially           </p></li>\r\n            <li><p>             Back cushions are fiber in synthetic ticking                        </p></li>\r\n            <li><p>             Benchmade                                                   </p></li>\r\n            <li><p>             Sinuous wire suspension                                             </p></li>\r\n            <li><p>             Made in Chile                                    </p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 32&quot;               </p></li>\r\n            <li><p>             Depth: 33&quot;                 </p></li> \r\n            <li><p>             Height: 31&quot;                </p></li> \r\n            <li><p>             SeatDepth: 21&quot;             </p></li> \r\n            <li><p>             Height: 17&quot;             </p></li>\r\n        </ul>\r\n    </div>\r\n</div> ', 'chair', 10740, 'bigChair5.jpg:bigChair5and1.jpg:bigChair5and2.jpg:bigChair5and3.jpg'),
(18, 'Blake Lounge Chair', 'chair6.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\n            An unexpected mix of materials espresso solid teak, handwoven natural rattan and chocolate top-grain, full-aniline leather with a handsome aged patina adds a great primitive/modern accent to the room. Handcrafted with attention to detail, there\'s even a strong webbed suspension under the woven rattan seat, and the cushions are plumped with polyfiber wrapped in ticking. A great chair in pairs.\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Solid teak        </p></li>\r\n            <li><p>             Sustainable, woven mesh                      </p></li>\r\n            <li><p>             Top-grain, full-aniline leather          </p></li>\r\n            <li><p>             Frame has an espresso finish               </p></li>\r\n            <li><p>             Eight-way, hand-tied spring suspension with partially           </p></li>\r\n            <li><p>             Back cushions are fiber in synthetic ticking                        </p></li>\r\n            <li><p>             Made in Indonesia and USA                                    </p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 30&quot;               </p></li>\r\n            <li><p>             Depth: 30&quot;                 </p></li> \r\n            <li><p>             Height: 34&quot;                </p></li> \r\n            <li><p>             SeatDepth: 21.5&quot;             </p></li> \r\n            <li><p>             Height: 5&quot;             </p></li>\r\n        </ul>\r\n    </div>\r\n</div> ', 'chair', 9920, 'bigChair6.jpg:bigChair6and1.jpg:bigChair6and2.jpg:bigChair6and3.jpg'),
(19, 'Ankara Chair', 'chair7.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\n            An eye-catching chair designed to be seen from every angle. Gracefully curved barrel back is precision-cut of mahogany veneer over engineered wood in an intricate pattern inspired by Indonesian mosaics. Solid mahogany frame flows seamlessly from the clean, contemporary sweep of the arms to the tapered back legs that follow the downward angle of the upper framework\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Plantation grown solid mahogany and mahogany veneer over engineered wood        </p></li>\r\n            <li><p>             Warm java finish and clear protective lacquer                        </p></li>\r\n            <li><p>             Seat cushion is soy-based polyfoam with fiber          </p></li>\r\n            <li><p>             Stain-resistant cushion cover is woven polyester          </p></li>\r\n            <li><p>             Back cushions are fiber in synthetic ticking                        </p></li>\r\n            <li><p>             Cushion is polyfoam with fiber in downproof ticking                                                 </p></li>\r\n            <li><p>             Cane seat with synthetic web suspension                                            </p></li>\r\n            <li><p>             Made in USA and Indonesia                                    </p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 29&quot;               </p></li>\r\n            <li><p>             Depth: 28&quot;                 </p></li> \r\n            <li><p>             Height: 30&quot;                </p></li> \r\n            <li><p>             SeatDepth: 26&quot;             </p></li> \r\n            <li><p>             Height: 18&quot;             </p></li>\r\n        </ul>\r\n    </div>\r\n</div> ', 'chair', 5780, 'bigChair7.jpg:bigChair7and1.jpg:bigChair7and2.jpg:bigChair7and3.jpg'),
(20, 'Tess Chair', 'chair8.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\n            Classic parlor style forgoes formality with contemporary proportions in a bold new hue. Tailored in a dimensional basketweave, rich texture accentuates deep purple tones from every sweeping curve. Alluring lines and refined pedigree relax into a low, loungey seat framed by a shapely back and curved track arms.\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Certified sustainable, kiln-dried hardwood frame       </p></li>\r\n            <li><p>             Seat cushion is soy-based polyfoam with fiber                        </p></li>\r\n            <li><p>             Back cushion is soy-based polyfoam with fiber        </p></li>\r\n            <li><p>             Sinuous wire spring suspension          </p></li>\r\n            <li><p>             Back cushions are fiber in synthetic ticking                        </p></li>\r\n            <li><p>             100% polyester fabric                                               </p></li>\r\n            <li><p>             Hardwood legs with jet stain                                          </p></li>\r\n            <li><p>             Made in Virginia, USA                                   </p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 32&quot;               </p></li>\r\n            <li><p>             Depth: 33&quot;                 </p></li> \r\n            <li><p>             Height: 35&quot;                </p></li> \r\n            <li><p>             SeatDepth: 22&quot;             </p></li> \r\n            <li><p>             Height: 17&quot;             </p></li>\r\n        </ul>\r\n    </div>\r\n</div> ', 'chair', 7850, 'bigChair8.jpg:bigChair8and1.jpg:bigChair8and2.jpg:bigChair8and3.jpg'),
(21, 'Hathaway Swivel Chair', 'chair9.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\n            Our oversized modern cottage look is as inviting as ever, but this time with a surprising turn. What looks like an overstuffed armchair is really a relaxing glider that not only rocks back and forth but swivels 360 degrees. Family-friendly slipcover in creamy white cotton-poly goes right in the washing machine.\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Sinuous wire spring suspension     </p></li>\r\n            <li><p>             Seat cushion is soy-based polyfoam with fiber                        </p></li>\r\n            <li><p>             Sinuous wire spring suspension          </p></li>\r\n            <li><p>             Back cushions are fiber in synthetic ticking                        </p></li>\r\n            <li><p>             100% polyester fabric                                               </p></li>\r\n            <li><p>             Machine wash removable slipcovers                                         </p></li>\r\n            <li><p>             Made in Argentina                                  </p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 29&quot;               </p></li>\r\n            <li><p>             Depth: 36&quot;                 </p></li> \r\n            <li><p>             Height: 30&quot;                </p></li> \r\n            <li><p>             SeatDepth: 36&quot;             </p></li> \r\n            <li><p>             Height: 34&quot;             </p></li>\r\n        </ul>\r\n    </div>\r\n</div> ', 'chair', 5780, 'bigChair9.jpg:bigChair9and1.jpg:bigChair9and2.jpg:bigChair9and3.jpg'),
(22, 'Barrington Chair', 'chair10.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\n            Contemporary looks borrow confidently from the classics in the Barrington with its low, wide look, distinctive lines, ample cushions and cool grey color outlined with contrasting taupe welting. The slim styling of the sloping track arms makes the most of seating space. Stylish comfort, scaled for a city apartment or smaller room.\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Seat cushion is soy-based polyfoam with feather-down blend wrap in downproof ticking     </p></li>\r\n            <li><p>             Back cushions are fiber in synthetic ticking                        </p></li>\r\n            <li><p>             Sinuous wire spring suspension                                              </p></li>\r\n            <li><p>             Solid maple, mocha stained legs                                        </p></li>\r\n            <li><p>             Made in Brazil                                 </p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 40&quot;               </p></li>\r\n            <li><p>             Depth: 40.5&quot;                 </p></li> \r\n            <li><p>             Height: 35.5&quot;                </p></li> \r\n            <li><p>             SeatDepth: 33.25&quot;             </p></li> \r\n            <li><p>             Height: 25&quot;             </p></li>\r\n        </ul>\r\n    </div>\r\n</div> ', 'chair', 6610, 'bigChair10.jpg:bigChair10and1.jpg:bigChair10and2.jpg:bigChair10and3.jpg'),
(23, 'Clara Chair', 'chair11.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\n            Super-soft graphite velvet embraces graceful parlor chair curves in a fresh take on tradition. Shapely tight back and slim arms frame a plump seat cushion all tailored with self welt detailing.\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Certified sustainable, kiln-dried hardwood frame    </p></li>\r\n            <li><p>             Tight back is soy-based polyfoam and fiber                        </p></li>\r\n            <li><p>             Tuxedo-stained hardwood legs                                             </p></li>\r\n            <li><p>             Upholstered in 100% polyester velvet                                       </p></li>\r\n            <li><p>             Benchmade                                      </p></li>\r\n            <li><p>             Made in Peru                                 </p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 30&quot;               </p></li>\r\n            <li><p>             Depth: 34.5&quot;                 </p></li> \r\n            <li><p>             Height: 34.5&quot;                </p></li> \r\n            <li><p>             SeatDepth: 22.25&quot;             </p></li> \r\n            <li><p>             Height: 20&quot;             </p></li>\r\n        </ul>\r\n    </div>\r\n</div> ', 'chair', 15710, 'bigChair11.jpg:bigChair11and1.jpg:bigChair11and2.jpg:bigChair11and3.jpg'),
(24, 'Donegal Chair', 'chair12.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\n            Refined retro plaid adds graphic punch and nubby texture to clean contemporary chair. Slim-lined frame makes the most of scaled-up grid of citrine, beige and taupe on tweedy charcoal.\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Tight back is soy-based polyfoam and fiber                        </p></li>\r\n            <li><p>             Tuxedo-stained hardwood legs                                             </p></li>\r\n            <li><p>             Upholstered in 100% polyester velvet                                       </p></li>\r\n            <li><p>             Hardwood legs with jet stain                                     </p></li>\r\n            <li><p>             Made in Sweden                                </p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 33&quot;               </p></li>\r\n            <li><p>             Depth: 36.5&quot;                 </p></li> \r\n            <li><p>             Height: 33.5&quot;                </p></li> \r\n            <li><p>             SeatDepth: 15.25&quot;             </p></li> \r\n          \r\n        </ul>\r\n    </div>\r\n</div> ', 'chair', 4120, 'bigChair12.jpg:bigChair12and1.jpg:bigChair12and2.jpg:bigChair12and3.jpg');
INSERT INTO `product` (`prodId`, `prodName`, `prodImage`, `prodDesc`, `type`, `price`, `bigImageNames`) VALUES
(25, 'Brown Chair', 'chair13.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\nOur reinterpretation of the leather wingback is a refined new classic, no tufts or fuss. Sheltering wings curve clean to narrow arms and straight lines at the base, all outlined in antiqued brass nailheads, each applied by hand the old-fashioned way. The heritage of fine leather continues; this top-grain leather, full-aniline dyed a dark java, marbled with high and low tones with a wax finish, will develop a rich patina over time. Hardwood legs taper square in distressed mahogany.\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Eco-friendly construction                       </p></li>\r\n            <li><p>             Certified sustainable kiln-dried hardwood frame                                           </p></li>\r\n            <li><p>             Seat cushion is soy-based polyfoam with fiber wrapped in feather-down blend                                       </p></li>\r\n            <li><p>             Tight back is soy-based polyfoam                                    </p></li>\r\n            <li><p>             Full-aniline leather                                </p></li>\r\n <li><p>             Nailhead trim                              </p></li>\r\n <li><p>             Made in France                                </p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 35&quot;               </p></li>\r\n            <li><p>             Depth: 40.5&quot;                 </p></li> \r\n            <li><p>             Height: 42.5&quot;                </p></li> \r\n            <li><p>             SeatDepth: 21.25&quot;             </p></li> \r\n          \r\n        </ul>\r\n    </div>\r\n</div> ', 'chair', 15000, 'bigChair13.jpg:bigChair13and1.jpg:bigChair13and2.jpg:bigChair13and3.jpg'),
(26, 'Avery Bomb Chest', 'chest1.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\nWe\'ve romanced a classic bombe shape with a cleaner, contemporary aesthetic. Sensuous curves from every angle are enhanced with warm caramel undertones in the slightly distressed charcoal finish. Three generous drawers are lined with hand-silkscreened paper in a black-on-cream vine pattern and finished with brushed nickel pulls.\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Solid poplar, red birch and engineered wood                       </p></li>\r\n            <li><p>             Medium-gloss black finish with clear protective lacquer                                         </p></li>\r\n            <li><p>             Dovetail joinery on drawers                                    </p></li>\r\n            <li><p>             Brushed nickel hardware                                   </p></li>\r\n            <li><p>             Made in China                                </p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 35&quot;               </p></li>\r\n            <li><p>             Depth: 20.5&quot;                 </p></li> \r\n            <li><p>             Height: 23.5&quot;                </p></li> \r\n            <li><p>             WoodDepth: 8.25&quot;             </p></li> \r\n            \r\n        </ul>\r\n    </div>\r\n</div> ', 'chest', 743, 'bigChest1.jpg:bigChest1and1.jpg:bigChest1and2.jpg:bigChest1and3.jpg'),
(27, 'Kavari Chest', 'chest2.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\nOur sleek new \"antique\" of richly grained acacia wood meets the modern demand for compact storage with open and closed spaces. Each piece is handcrafted with tongue-and-groove joinery and hand-finished with a two-tone distressing technique that produces a rich, glowing brown patina with undertones of black. \r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Acacia wood                       </p></li>\r\n            <li><p>             Multistep hand-finish                                            </p></li>\r\n            <li><p>             Iron hinges, handle and knobs with antiqued bronze finish                                      </p></li>\r\n            <li><p>             Three drawers                                  </p></li>\r\n            <li><p>             Cord management cutouts                                </p></li>\r\n            <li><p>             Made in India                                </p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 40&quot;               </p></li>\r\n            <li><p>             Depth: 20&quot;                 </p></li> \r\n            <li><p>             Height: 28&quot;                </p></li> \r\n        </ul>\r\n            <h5>Door Overall:</h5>\r\n        <ul>\r\n            <li><p>             Width: 21&quot;               </p></li>\r\n            <li><p>             Depth: 17&quot;                 </p></li> \r\n            <li><p>             Height: 21&quot;                </p></li>\r\n       </ul> \r\n           <h5>Shelf Overall:</h5>\r\n        <ul>\r\n            <li><p>             Width: 21&quot;               </p></li>\r\n            <li><p>             Depth: 17&quot;                 </p></li> \r\n            <li><p>             Height: 0.5&quot;                </p></li> \r\n        </ul>\r\n    </div>\r\n</div> ', 'chest', 495, 'bigChest2.jpg:bigChest2and1.jpg:bigChest2and2.jpg:bigChest2and3.jpg'),
(28, 'Rojo Chest', 'chest3.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\nWith all the warmth and rustic charm of a one-of-a-kind antique, the rich waxed patina of this red storage cabinet adds instant character to any room. Crafted of shesham and mango wood with traditional tongue-and-groove joinery, the cabinet is topped with architectural crown moulding.\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Sustainable shesham and mango wood                       </p></li>\r\n            <li><p>             Red lacquer finish with pigmented wax                                           </p></li>\r\n            <li><p>             Iron hinges and knobs                                       </p></li>\r\n            <li><p>             Two adjustable shelves                                     </p></li>\r\n            <li><p>             Cord management with sliding door                               </p></li>\r\n            <li><p>             Made in India                                              </p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 46&quot;               </p></li>\r\n            <li><p>             Depth: 18&quot;                 </p></li> \r\n            <li><p>             Height: 34&quot;                </p></li> \r\n        </ul>\r\n      <h5>Door Overall:</h5>\r\n        <ul>\r\n            <li><p>             Width: 18&quot;               </p></li>\r\n            <li><p>             Depth: 15&quot;                 </p></li> \r\n            <li><p>             Height: 25&quot;                </p></li>\r\n        </ul> \r\n           <h5>Shelf Overall:</h5>\r\n        <ul>\r\n            <li><p>             Width: 20&quot;               </p></li>\r\n            <li><p>             Depth: 14&quot;                 </p></li> \r\n            <li><p>             Height: 0.5&quot;                </p></li> \r\n        </ul>\r\n    </div>\r\n</div> ', 'chest', 661, 'bigChest3.jpg:bigChest3and1.jpg:bigChest3and2.jpg:bigChest3and3.jpg'),
(29, 'Kavar 40 Chest', 'chest4.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\nOur sleek new \"antique\" of richly grained acacia wood warms the entryway with the look of a well-loved family heirloom. Classic cabinet has one fixed shelf and two storage drawers. Each piece is constructed with mortise-and-tenon joinery and hand-finished with a two-tone distressing technique that produces a rich, glowing brown patina with undertones of black. Clean crown moulding, raised panel doors and hand-finished iron hardware add character.\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Acacia wood                      </p></li>\r\n            <li><p>             Edge-to-edge planks and tongue-and-groove frame joinery                                          </p></li>\r\n            <li><p>             Iron hardware                                      </p></li>\r\n            <li><p>             Lacquer finish                                  </p></li>\r\n            <li><p>             Two drawers with wood channel glides and stoppers                              </p></li>\r\n            <li><p>             One fixed shelf                                            </p></li>\r\n            <li><p>             Made in Venezuela                                           </p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 40&quot;               </p></li>\r\n            <li><p>             Depth: 15&quot;                 </p></li> \r\n            <li><p>             Height: 36&quot;                </p></li> \r\n        </ul>\r\n      <h5>Door Overall:</h5>\r\n        <ul>\r\n            <li><p>             Width: 18&quot;               </p></li>\r\n            <li><p>             Depth: 12&quot;                 </p></li> \r\n            <li><p>             Height: 23&quot;                </p></li>\r\n        </ul> \r\n           <h5>Shelf Overall:</h5>\r\n        <ul>\r\n            <li><p>             Width: 18&quot;               </p></li>\r\n            <li><p>             Depth: 12&quot;                 </p></li> \r\n            <li><p>             Height: 10&quot;                </p></li> \r\n        </ul>\r\n    </div>\r\n</div> \r\n', 'chest', 495, 'bigChest4.jpg:bigChest4and1.jpg:bigChest4and2.jpg:bigChest4and3.jpg'),
(30, 'Dawson Chest', 'chest5.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\nOur architectural Paterson collection is inspired by built-in cabinetry from turn-of-the-century homes. Contemporary cabinet with a touch of cottage styling features stepped moulding, elegant tapered legs, a white lacquer finish and brushed nickel handles. Arts-and-Crafts style windowpane doors open to two adjustable shelves.\r\n\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Solid hardwood and low-emission engineered wood                       </p></li>\r\n            <li><p>             White lacquer finish                                          </p></li>\r\n            <li><p>             Brushed nickel hardware                                      </p></li>\r\n            <li><p>             Tempered glass door panes                                     </p></li>\r\n            <li><p>             Two adjustable shelves                              </p></li>\r\n            <li><p>             Made in Thailand                                              </p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 36&quot;               </p></li>\r\n            <li><p>             Depth: 15&quot;                 </p></li> \r\n            <li><p>             Height: 49&quot;                </p></li> \r\n        </ul>\r\n      <h5>Door Overall:</h5>\r\n        <ul>\r\n            <li><p>             Width: 33&quot;               </p></li>\r\n            <li><p>             Depth: 14&quot;                 </p></li> \r\n            <li><p>             Height: 22&quot;                </p></li>\r\n        </ul> \r\n           <h5>Shelf Overall:</h5>\r\n        <ul>\r\n            <li><p>             Width: 32&quot;               </p></li>\r\n            <li><p>             Depth: 12&quot;                 </p></li> \r\n            <li><p>             Height: 42&quot;                </p></li> \r\n        </ul>\r\n    </div>\r\n</div> \r\n', 'chest', 495, 'bigChest5.jpg:bigChest5and1.jpg:bigChest5and2.jpg:bigChest5and3.jpg'),
(31, 'Parker Spirit Chest', 'chest6.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\nThere\'s more than meets the eye in our new compact entertainment bar. Two bartop leaves flip open to perch drinks and snacks, while revealing generous bottle storage. Front door drops down to create an open serving area. Below are a drawer for tools and an 18-bottle wine bin. Side shelves (three on the left, two on the right) store stemware or bottles. Finished back panel lets Parker be the center of the party.\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Solid birch, solid ash and ash veneer, low-emission engineered wood                       </p></li>\r\n            <li><p>             Black lacquer finish                                          </p></li>\r\n            <li><p>             Brushed nickel-finish pulls                                      </p></li>\r\n        \r\n            <li><p>             Made in Columbia                                              </p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 33&quot;               </p></li>\r\n            <li><p>             Depth: 16&quot;                 </p></li> \r\n            <li><p>             Height: 36&quot;                </p></li> \r\n        </ul>\r\n      <h5>Door Overall:</h5>\r\n        <ul>\r\n            <li><p>             Width: 44&quot;               </p></li>\r\n            <li><p>             Depth: 16&quot;                 </p></li> \r\n            <li><p>             Height: 37&quot;                </p></li>\r\n        </ul> \r\n           <h5>Shelf Overall:</h5>\r\n        <ul>\r\n            <li><p>             Width: 21&quot;               </p></li>\r\n            <li><p>             Depth: 9&quot;                 </p></li> \r\n            <li><p>             Height: 25&quot;                </p></li> \r\n        </ul>\r\n    </div>\r\n</div> ', 'chest', 661, 'bigChest6.jpg:bigChest6and1.jpg:bigChest6and2.jpg:bigChest6and3.jpg'),
(32, 'Ainsworth Chest', 'chest7.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\nTimeless styling and a versatile collection of pieces with glass and wood panel options offer media, storage and workspace solutions for every setting. American-crafted cabinetry showcases a return to walnut with its lighter mid-tone hue and minimal figured grain. Natural oil and wax finish highlights and nourishes the wood.\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Solid American walnut, walnut veneer and low-emission engineered wood                       </p></li>\r\n            <li><p>             Natural oil and wax finish                                          </p></li>\r\n            <li><p>             Zinc hardware with a natural steel finish                                      </p></li>\r\n            <li><p>             Includes both wood and glass door panels                                    </p></li>\r\n            <li><p>             Three adjustable shelves                              </p></li>\r\n            <li><p>             Made in USA                                            </p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 40&quot;               </p></li>\r\n            <li><p>             Depth: 17&quot;                 </p></li> \r\n            <li><p>             Height: 60&quot;                </p></li> \r\n        </ul>\r\n      <h5>Door Overall:</h5>\r\n        <ul>\r\n            <li><p>             Width: 34&quot;               </p></li>\r\n            <li><p>             Depth: 16&quot;                 </p></li> \r\n            <li><p>             Height: 48&quot;                </p></li>\r\n        </ul> \r\n           <h5>Shelf Overall:</h5>\r\n        <ul>\r\n            <li><p>             Width: 35&quot;               </p></li>\r\n            <li><p>             Depth: 42&quot;                 </p></li> \r\n            <li><p>             Height: 32.5&quot;                </p></li> \r\n        </ul>\r\n    </div>\r\n</div> ', 'chest', 1323, 'bigChest7.jpg:bigChest7and1.jpg:bigChest7and2.jpg'),
(33, 'Varick Chest', 'chest8.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\nElongated solid brass pulls make a symmetrical play of storage in tall slender cabinet that leaves a small footprint with maximum presence. Revealing glass-paneled oak-veneered doors open to three shelves with a plate rail on the top shelf. A generous drawer below stows linens, trays or odds and ends.\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Double oak veneer and low-emission engineered wood                      </p></li>\r\n            <li><p>             Durable lacquer coffee finish                                           </p></li>\r\n            <li><p>             One fixed and two adjustable shelves                                       </p></li>\r\n            <li><p>             Solid brass handles                                    </p></li>\r\n            <li><p>             Anti-tip hardware included                               </p></li>\r\n            <li><p>             Made in Chile                                              </p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 40&quot;               </p></li>\r\n            <li><p>             Depth: 16.5&quot;                 </p></li> \r\n            <li><p>             Height: 76&quot;                </p></li> \r\n        </ul>\r\n  \r\n    </div>\r\n</div> ', 'chest', 743, 'bigChest8.jpg:bigChest8and1.jpg:bigChest8and2.jpg:bigChest8and3.jpg'),
(34, 'Hunter Chest', 'chest9.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\nInspired by a vintage steamer trunk, our updated steamer bar cabinet opens to reveal a capacious home bar. Crafted of American ash solids and veneers with a distinctive recessed panel grid design, rich ebony finish and satin silver finished hardware. Storage includes two fixed shelves, bottle storage on both doors, laminate fold-out top, pull-out glass racks for up to 30 wine glasses and 20 drinking glasses, and an accessory drawer.\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             American ash solids and veneers                     </p></li>\r\n            <li><p>             Hand-stained with an oil topcoat                                           </p></li>\r\n            <li><p>             Doweled joinery with dovetailed drawer boxes                                       </p></li>\r\n            <li><p>             Nickel-plated solid brass hardware                                   </p></li>\r\n            <li><p>             Two fixed shelves                              </p></li>\r\n            <li><p>             Made in Philippines                                              </p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 37&quot;               </p></li>\r\n            <li><p>             Depth: 21&quot;                 </p></li> \r\n            <li><p>             Height: 42&quot;                </p></li> \r\n        </ul>\r\n      <h5>When Fully Opened:</h5>\r\n        <ul>\r\n            <li><p>             Width: 72&quot;               </p></li>\r\n            <li><p>             Depth: 21.5&quot;                 </p></li> \r\n            <li><p>             Height: 42&quot;                </p></li>\r\n        </ul> \r\n           \r\n      \r\n    </div>\r\n</div> ', 'chest', 854, 'bigChest9.jpg:bigChest9and1.jpg:bigChest9and2.jpg:bigChest9and3.jpg'),
(35, 'Marin Chest', 'chest10.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\nCenturies of Chinese craftmanship meet mid-century modern in a warm, minimal classic. Crafted of solid weathered elm with traditional wood-on-wood joinery techniques without the use of nails or screws this contemporary cabinet combines generous storage with striking clean lines. A multi-step tung tree oil finish, a natural oil derived from the seeds of the tung tree nut, brings out the sweeping grain and preserves the beauty of the wood. Each door with solid steel pulls features built-in storage for bottles and barware.\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Created in collaboration with designer Maria Yee                     </p></li>\r\n            <li><p>             Solid elm                                           </p></li>\r\n            <li><p>             Traditional wood-on-wood joinery                                       </p></li>\r\n            <li><p>             Tung tree oil exterior finish, water-based interior finish                                   </p></li>\r\n            <li><p>             Five shelves (one fixed, one adjustable, three adjustable                               </p></li>\r\n            <li><p>             Made in Mexico                                              </p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 37&quot;               </p></li>\r\n            <li><p>             Depth: 21.5&quot;                 </p></li> \r\n            <li><p>             Height: 42&quot;                </p></li> \r\n        </ul>\r\n     \r\n    </div>\r\n</div> ', 'chest', 495, 'bigChest10.jpg:bigChest10and1.jpg:bigChest10and2.jpg:bigChest10and3.jpg'),
(36, 'Steamer Chest', 'chest11.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\nOur refined yet rustic trunk table is crafted of solid shesham wood with a warm clove finish, beautiful beveled panels and traditional iron hardware. Top with safety hinges opens up to generous, deep storage with features including a removable serving tray and removable dividers for stashing up to eight bottles of wine.\r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Solid shesham wood                       </p></li>\r\n            <li><p>             Clove lacquer finish                                          </p></li>\r\n            <li><p>             Iron hardware with clear powdercoat finish                                       </p></li>\r\n            <li><p>             Two adjustable shelves                                     </p></li>\r\n            \r\n            <li><p>             Made in Canada                                            </p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 44&quot;               </p></li>\r\n            <li><p>             Depth: 24&quot;                 </p></li> \r\n            <li><p>             Height: 18&quot;                </p></li> \r\n        </ul>\r\n      \r\n       \r\n    </div>\r\n</div> ', 'chest', 570, 'bigChest11.jpg:bigChest11and1.jpg:bigChest11and2.jpg:bigChest11and3.jpg'),
(37, 'Calasis Chest', 'chest12.jpg', '<div id=\'prodDescDiv\'>\r\n    <div id=\'descDiv1\'>\r\n        <h4>Overview</h4>\r\n        <p>\r\nTimeless styling and a versatile collection of pieces with glass and wood panel options offer media, storage and workspace solutions for every setting. American-crafted cabinetry showcases a return to walnut with its lighter mid-tone hue and minimal figured grain. Natural oil and wax finish highlights and nourishes the wood. Interchangeable door panels easily allow transition from open to closed storage. \r\n        </p>\r\n        <hr class=\'thinLine\'/>!!stop!!\r\n       \r\n        <hr class=\'thinLine\'/>\r\n        <h4>Details and Dimensions</h4>\r\n        <ul>\r\n            <li><p>             Solid American walnut, walnut veneer and low-emission engineered wood                      </p></li>\r\n            <li><p>             Natural oil and wax finish                                           </p></li>\r\n            <li><p>             Zinc hardware with a natural steel finish                                       </p></li>\r\n            <li><p>             Includes both wood and glass door panels                                    </p></li>\r\n            <li><p>             Three adjustable shelves                               </p></li>\r\n            <li><p>             Cord management/ventilation cutout                                              </p></li>\r\n            <li><p>             Made in Vietnam                                              </p></li>\r\n        </ul>\r\n        <hr/>\r\n        <h4>Overall Dimensions:</h4>\r\n        <ul>\r\n            <li><p>             Width: 40&quot;               </p></li>\r\n            <li><p>             Depth: 17&quot;                 </p></li> \r\n            <li><p>             Height: 60&quot;                </p></li> \r\n        </ul>\r\n      <h5>Overall interior:</h5>\r\n        <ul>\r\n            <li><p>             Width: 34.75&quot;               </p></li>\r\n            <li><p>             Depth: 16&quot;                 </p></li> \r\n            <li><p>             Height: 48&quot;                </p></li>\r\n        </ul> \r\n        \r\n    </div>\r\n</div> ', 'chest', 755, 'bigChest12.jpg:bigChest12and1.jpg:bigChest12and2.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `customer`
--
ALTER TABLE `customer`
  ADD PRIMARY KEY (`customerId`);

--
-- Indexes for table `orders`
--
ALTER TABLE `orders`
  ADD PRIMARY KEY (`orderId`);

--
-- Indexes for table `product`
--
ALTER TABLE `product`
  ADD PRIMARY KEY (`prodId`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `customer`
--
ALTER TABLE `customer`
  MODIFY `customerId` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `orders`
--
ALTER TABLE `orders`
  MODIFY `orderId` int(7) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `product`
--
ALTER TABLE `product`
  MODIFY `prodId` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=38;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
